-- =====================================================
-- BuilderMaps: Add Diverse Spots (Cafes, Hacker Houses, Communities)
-- Run this in Supabase SQL Editor to populate missing categories
-- =====================================================

-- =====================================================
-- SAN FRANCISCO (needs more cafes, communities)
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('sf-sightglass-soma', 'Sightglass Coffee SOMA', 'san-francisco', ARRAY['cafe'], 'Industrial-chic coffee roaster with excellent pour-overs. The large communal tables and reliable WiFi make it a favorite among startup founders for casual meetings and focused work sessions.', ARRAY[-122.4007, 37.7785], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/sightglasssoma', 'https://sightglasscoffee.com', 'https://x.com/saboressf', 'buildermaps', true),
('sf-ritual-valencia', 'Ritual Coffee Roasters', 'san-francisco', ARRAY['cafe'], 'Mission District institution known for direct-trade coffee and laptop-friendly environment. The Valencia Street location has become an unofficial tech networking spot with great natural light.', ARRAY[-122.4208, 37.7562], ARRAY['good coffee', 'fast wifi', 'indie hackers', 'outdoor seating'], 'https://maps.app.goo.gl/ritualcoffee', 'https://ritualroasters.com', NULL, 'buildermaps', true),
('sf-noisebridge', 'Noisebridge Hackerspace', 'san-francisco', ARRAY['community'], 'Legendary anarchist hackerspace in the Mission. Open to all for electronics, programming, crafts, and collaboration. The birthplace of countless startups and a true SF institution since 2007.', ARRAY[-122.4194, 37.7625], ARRAY['open community', 'beginner friendly', '24/7 access', 'events'], 'https://maps.app.goo.gl/noisebridge', 'https://noisebridge.net', 'https://x.com/noabordebridge', 'buildermaps', true),
('sf-south-park', 'South Park Commons', 'san-francisco', ARRAY['community'], 'Membership community for founders and technologists exploring their next chapter. Strong focus on AI/ML builders with regular talks, dinners, and warm introductions to investors.', ARRAY[-122.3937, 37.7827], ARRAY['founders only', 'networking', 'mentorship', 'ai builders'], 'https://maps.app.goo.gl/southparkcommons', 'https://southparkcommons.com', 'https://x.com/southparkcommon', 'buildermaps', true);

-- =====================================================
-- NEW YORK
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('nyc-hacker-house-bushwick', 'Bushwick Generator', 'new-york', ARRAY['hacker-house'], 'Coliving and coworking space for founders in Brooklyn. Monthly residencies available with demo nights and investor connections. Strong web3 and creative tech community.', ARRAY[-73.9212, 40.6944], ARRAY['crypto crowd', 'networking', 'events', 'demo days'], 'https://maps.app.goo.gl/bushwickgenerator', NULL, NULL, 'buildermaps', true),
('nyc-think-coffee', 'Think Coffee Mercer', 'new-york', ARRAY['cafe'], 'Fair trade coffee shop near NYU that has become a hub for student founders and early-stage builders. Spacious basement level perfect for longer work sessions.', ARRAY[-73.9957, 40.7267], ARRAY['good coffee', 'fast wifi', 'beginner friendly', 'power outlets'], 'https://maps.app.goo.gl/thinkcoffee', 'https://thinkcoffee.com', NULL, 'buildermaps', true),
('nyc-787-coffee', '787 Coffee', 'new-york', ARRAY['cafe'], 'Puerto Rican specialty coffee with multiple Manhattan locations. The Lexington Ave spot is known for attracting tech workers from nearby offices. Great espresso and work-friendly vibes.', ARRAY[-73.9777, 40.7528], ARRAY['good coffee', 'fast wifi', 'casual', 'power outlets'], 'https://maps.app.goo.gl/787coffee', 'https://787coffee.com', 'https://x.com/787coffee', 'buildermaps', true),
('nyc-on-deck', 'On Deck NYC Hub', 'new-york', ARRAY['community'], 'New York gathering space for On Deck fellows and alumni. Regular events, working sessions, and founder dinners. Strong network for early-stage founders across all verticals.', ARRAY[-74.0060, 40.7128], ARRAY['founders only', 'networking', 'mentorship', 'events'], 'https://maps.app.goo.gl/ondecknyc', 'https://beondeck.com', 'https://x.com/beaborondeck', 'buildermaps', true),
('nyc-recurse-center', 'Recurse Center', 'new-york', ARRAY['community', 'hacker-house'], 'Self-directed educational retreat for programmers. Free 6 or 12-week batches in Brooklyn. Alumni network includes engineers at top companies and successful founders.', ARRAY[-73.9614, 40.7081], ARRAY['deep focus', 'beginner friendly', 'mentorship', 'open community'], 'https://maps.app.goo.gl/recursecenter', 'https://recurse.com', 'https://x.com/recursecenter', 'buildermaps', true);

-- =====================================================
-- LONDON
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('london-hacker-house-shoreditch', 'Founders House London', 'london', ARRAY['hacker-house'], 'Coliving for founders in Shoreditch. Mix of short and long-term stays with regular community dinners. Strong fintech and AI founder presence.', ARRAY[-0.0777, 51.5246], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/foundershouseldn', NULL, NULL, 'buildermaps', true),
('london-ozone-coffee', 'Ozone Coffee Roasters', 'london', ARRAY['cafe'], 'New Zealand-style specialty coffee in Shoreditch with a spacious upstairs area perfect for working. Popular among local startup teams for informal meetings.', ARRAY[-0.0863, 51.5253], ARRAY['good coffee', 'fast wifi', 'networking', 'meeting rooms'], 'https://maps.app.goo.gl/ozonecoffee', 'https://ozonecoffee.co.uk', 'https://x.com/oaboronecoffee', 'buildermaps', true),
('london-tab-centre', 'The Tab Centre', 'london', ARRAY['cafe'], 'Hidden gem in Shoreditch with excellent coffee and a basement workspace. Known for attracting creative tech workers and designers. No time limits on seating.', ARRAY[-0.0762, 51.5238], ARRAY['good coffee', 'deep focus', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/tabcentre', NULL, NULL, 'buildermaps', true),
('london-founders-forum', 'Founders Forum Hub', 'london', ARRAY['community'], 'Invite-only community for growth-stage founders. Regular programming includes founder dinners, expert sessions, and investor introductions. Strong European network.', ARRAY[-0.1426, 51.5188], ARRAY['founders only', 'networking', 'mentorship', 'vc sightings'], 'https://maps.app.goo.gl/foundersforum', 'https://foundersforum.eu', 'https://x.com/foaborundersforum', 'buildermaps', true),
('london-newspeak-house', 'Newspeak House', 'london', ARRAY['community', 'hacker-house'], 'Independent residential college for political and civic technologists in Bethnal Green. Regular public events, workshops, and a strong community of mission-driven builders.', ARRAY[-0.0558, 51.5271], ARRAY['open community', 'events', 'networking', 'beginner friendly'], 'https://maps.app.goo.gl/newspeakhouse', 'https://newspeak.house', 'https://x.com/newspeakhouse', 'buildermaps', true);

-- =====================================================
-- BERLIN
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('berlin-hacker-house-mitte', 'Silicon Allee Residency', 'berlin', ARRAY['hacker-house'], 'Founder coliving in Mitte with dedicated workspace. Monthly programming includes pitch practice and investor office hours. Strong international founder community.', ARRAY[13.3888, 52.5200], ARRAY['founders only', 'networking', 'demo days', 'fast wifi'], 'https://maps.app.goo.gl/siliconallee', 'https://siliconallee.com', NULL, 'buildermaps', true),
('berlin-the-barn', 'The Barn Coffee Roasters', 'berlin', ARRAY['cafe'], 'Specialty coffee pioneer in Berlin with minimalist Scandinavian design. The Mitte location is a known tech hangout with excellent pour-overs and work-friendly atmosphere.', ARRAY[13.4016, 52.5262], ARRAY['good coffee', 'deep focus', 'quiet zone', 'fast wifi'], 'https://maps.app.goo.gl/thebarnberlin', 'https://thebarn.de', 'https://x.com/thebarnberlin', 'buildermaps', true),
('berlin-father-carpenter', 'Father Carpenter', 'berlin', ARRAY['cafe'], 'Australian-style coffee shop in Mitte popular with remote workers and founders. Great breakfast options and a relaxed vibe perfect for morning work sessions.', ARRAY[13.4049, 52.5277], ARRAY['good coffee', 'fast wifi', 'casual', 'outdoor seating'], 'https://maps.app.goo.gl/fathercarpenter', NULL, NULL, 'buildermaps', true),
('berlin-c-base', 'c-base Hackerspace', 'berlin', ARRAY['community'], 'Legendary Berlin hackerspace founded in 1995, located in a "crashed space station." Hub for CCC community, hackathons, and digital rights activism. Open to visitors on Tuesdays.', ARRAY[13.4200, 52.5128], ARRAY['open community', 'events', '3am friendly', 'crypto crowd'], 'https://maps.app.goo.gl/cbase', 'https://c-base.org', 'https://x.com/caborbase', 'buildermaps', true),
('berlin-factory', 'Factory Berlin Community', 'berlin', ARRAY['community'], 'Large-scale tech campus with community programming beyond just coworking. Regular founder events, corporate innovation meetups, and strong connections to Berlin startup ecosystem.', ARRAY[13.4529, 52.5082], ARRAY['networking', 'events', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/factoryberlin', 'https://factoryberlin.com', 'https://x.com/factoryberlin', 'buildermaps', true);

-- =====================================================
-- LISBON
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('lisbon-hacker-house-santos', 'Startup House Lisbon', 'lisbon', ARRAY['hacker-house'], 'Coliving for international founders in Santos neighborhood. Rooftop workspace with river views. Strong digital nomad community with weekly networking events.', ARRAY[-9.1524, 38.7069], ARRAY['founders only', 'rooftop vibes', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/startuphousalisbon', NULL, NULL, 'buildermaps', true),
('lisbon-fabrica-coffee', 'Fabrica Coffee Roasters', 'lisbon', ARRAY['cafe'], 'Specialty coffee in a converted warehouse in Santos. Large communal tables and industrial aesthetic make it popular with remote workers and startup teams.', ARRAY[-9.1485, 38.7082], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/fabricacoffee', 'https://fabricacoffeeroasters.com', NULL, 'buildermaps', true),
('lisbon-copenhagen-coffee', 'Copenhagen Coffee Lab', 'lisbon', ARRAY['cafe'], 'Danish specialty coffee in Chiado. Known for excellent WiFi and laptop-friendly policy. Multiple floors provide options for meetings or focused solo work.', ARRAY[-9.1416, 38.7104], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/copenhagencoffee', 'https://copenhagencoffeelab.com', NULL, 'buildermaps', true),
('lisbon-startup-lisboa', 'Startup Lisboa Community', 'lisbon', ARRAY['community'], 'Lisbon main startup incubator with strong community programming. Regular pitch events, mentor office hours, and connections to Portuguese investor ecosystem.', ARRAY[-9.1393, 38.7107], ARRAY['networking', 'mentorship', 'demo days', 'beginner friendly'], 'https://maps.app.goo.gl/startuplisboa', 'https://startuplisboa.com', 'https://x.com/startuplisboa', 'buildermaps', true),
('lisbon-beta-i', 'Beta-i Innovation Hub', 'lisbon', ARRAY['community'], 'Innovation community connecting startups with corporates. Strong programming around open innovation, accelerator batches, and founder networking events.', ARRAY[-9.1467, 38.7227], ARRAY['networking', 'events', 'mentorship', 'vc sightings'], 'https://maps.app.goo.gl/betai', 'https://beta-i.com', 'https://x.com/betaborai', 'buildermaps', true);

-- =====================================================
-- AMSTERDAM
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('amsterdam-hacker-house-oost', 'Founder Residency Amsterdam', 'amsterdam', ARRAY['hacker-house'], 'Coliving space for startup founders in Amsterdam Oost. Mix of Dutch and international founders with regular community dinners and investor intros.', ARRAY[4.9273, 52.3614], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/founderresidency', NULL, NULL, 'buildermaps', true),
('amsterdam-lot-sixty-one', 'Lot Sixty One Coffee', 'amsterdam', ARRAY['cafe'], 'Specialty coffee roaster in Kinkerstraat with spacious seating and great natural light. Popular among local tech workers for morning focus sessions.', ARRAY[4.8679, 52.3673], ARRAY['good coffee', 'fast wifi', 'deep focus', 'power outlets'], 'https://maps.app.goo.gl/lotsixtyonea', 'https://lotsixtyone.com', NULL, 'buildermaps', true),
('amsterdam-scandinavian-embassy', 'Scandinavian Embassy', 'amsterdam', ARRAY['cafe'], 'Nordic-style coffee and pastries in De Pijp. The upstairs area is perfect for laptop work with reliable WiFi and excellent cinnamon buns.', ARRAY[4.8934, 52.3541], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'casual'], 'https://maps.app.goo.gl/scandinavianembassy', 'https://scandinavianembassy.nl', NULL, 'buildermaps', true),
('amsterdam-techstars', 'Techstars Amsterdam Hub', 'amsterdam', ARRAY['community'], 'Hub for Techstars alumni and broader Amsterdam startup community. Regular events, mentorship sessions, and strong connections to European tech ecosystem.', ARRAY[4.9041, 52.3676], ARRAY['networking', 'mentorship', 'demo days', 'vc sightings'], 'https://maps.app.goo.gl/techstarsamsa', 'https://techstars.com', 'https://x.com/techstars', 'buildermaps', true),
('amsterdam-hackers-founders', 'Hackers & Founders Amsterdam', 'amsterdam', ARRAY['community'], 'Monthly meetup community for technical founders. Events feature founder talks, demos, and networking. One of the most active founder communities in Netherlands.', ARRAY[4.8952, 52.3702], ARRAY['networking', 'events', 'indie hackers', 'beginner friendly'], 'https://maps.app.goo.gl/hackersfoundersa', 'https://hackersandfounders.nl', 'https://x.com/haborackersfoundersnl', 'buildermaps', true);

-- =====================================================
-- PARIS
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('paris-hacker-house-marais', 'Founders Residence Paris', 'paris', ARRAY['hacker-house'], 'Coliving for early-stage founders in Le Marais. Beautiful Haussmann building with dedicated workspace. Strong French tech ecosystem connections.', ARRAY[2.3602, 48.8580], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/foundersresidenceparis', NULL, NULL, 'buildermaps', true),
('paris-honor-cafe', 'Honor Café', 'paris', ARRAY['cafe'], 'Specialty coffee near Canal Saint-Martin popular with Paris tech scene. Known for excellent flat whites and work-friendly atmosphere with good WiFi.', ARRAY[2.3650, 48.8720], ARRAY['good coffee', 'fast wifi', 'casual', 'power outlets'], 'https://maps.app.goo.gl/honorcafe', NULL, NULL, 'buildermaps', true),
('paris-la-fontaine', 'La Fontaine de Belleville', 'paris', ARRAY['cafe'], 'Historic café in Belleville transformed into specialty coffee destination. Large space with multiple rooms, perfect for longer work sessions or team meetings.', ARRAY[2.3794, 48.8720], ARRAY['good coffee', 'fast wifi', 'networking', 'meeting rooms'], 'https://maps.app.goo.gl/lafontainea', 'https://bellfreville-brulerie.com', NULL, 'buildermaps', true),
('paris-station-f-community', 'Station F Community', 'paris', ARRAY['community'], 'Beyond the campus - Station F community programming includes founder events, corporate partnerships, and one of Europe largest startup networks.', ARRAY[2.3696, 48.8346], ARRAY['networking', 'events', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/stationfparis', 'https://stationf.co', 'https://x.com/joinstationf', 'buildermaps', true),
('paris-numa', 'NUMA Paris', 'paris', ARRAY['community'], 'Open innovation hub with strong community focus. Regular events on AI, climate tech, and social impact. Good connections to French corporate innovation teams.', ARRAY[2.3499, 48.8673], ARRAY['networking', 'events', 'mentorship', 'beginner friendly'], 'https://maps.app.goo.gl/numaparis', 'https://numa.co', 'https://x.com/numahq', 'buildermaps', true);

-- =====================================================
-- TOKYO
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('tokyo-hacker-house-shibuya', 'Mistletoe Basecamp', 'tokyo', ARRAY['hacker-house'], 'Founder coliving and workspace in Shibuya backed by prominent Japanese VCs. Regular programming connects international founders with Japan market opportunities.', ARRAY[139.6989, 35.6595], ARRAY['founders only', 'networking', 'mentorship', 'fast wifi'], 'https://maps.app.goo.gl/mistletoebasecamp', NULL, NULL, 'buildermaps', true),
('tokyo-blue-bottle-shinjuku', 'Blue Bottle Coffee Shinjuku', 'tokyo', ARRAY['cafe'], 'Bay Area coffee culture in Tokyo. The Shinjuku location has ample seating and attracts tech workers from nearby offices. Excellent pour-overs and work-friendly policy.', ARRAY[139.6917, 35.6895], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/bluebottleshinjuku', 'https://bluebottlecoffee.jp', NULL, 'buildermaps', true),
('tokyo-streamer-coffee', 'Streamer Coffee Company', 'tokyo', ARRAY['cafe'], 'Specialty coffee in Shibuya known for latte art and tech-friendly atmosphere. Popular among startup teams for informal meetings and focus work.', ARRAY[139.6967, 35.6567], ARRAY['good coffee', 'fast wifi', 'casual', 'networking'], 'https://maps.app.goo.gl/streamercoffee', 'https://streamercoffee.com', NULL, 'buildermaps', true),
('tokyo-code-chrysalis', 'Code Chrysalis Community', 'tokyo', ARRAY['community'], 'English-language coding bootcamp with strong alumni community. Regular meetups, tech talks, and networking events for both Japanese and international builders.', ARRAY[139.7454, 35.6585], ARRAY['beginner friendly', 'events', 'networking', 'mentorship'], 'https://maps.app.goo.gl/codechrysalis', 'https://codechrysalis.io', 'https://x.com/codechrysalis', 'buildermaps', true),
('tokyo-slush-tokyo', 'Slush Tokyo Community', 'tokyo', ARRAY['community'], 'Year-round community building around the annual Slush Tokyo event. Regular founder meetups and strong connections to Nordic and European startup ecosystems.', ARRAY[139.7670, 35.6814], ARRAY['networking', 'events', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/slushtokyo', 'https://tokyo.slush.org', 'https://x.com/slushtokyo', 'buildermaps', true);

-- =====================================================
-- SINGAPORE
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('singapore-hacker-house-tiong', 'Entrepreneur First Residency', 'singapore', ARRAY['hacker-house'], 'Coliving for EF cohort members and alumni in Tiong Bahru. Strong community of technical founders building deep tech companies.', ARRAY[103.8318, 1.2862], ARRAY['founders only', 'ai builders', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/efresidencysg', NULL, NULL, 'buildermaps', true),
('singapore-common-man', 'Common Man Coffee Roasters', 'singapore', ARRAY['cafe'], 'Specialty coffee with multiple locations. The CHIJMES outlet is popular with startup folks for its spacious setting and reliable WiFi.', ARRAY[103.8527, 1.2955], ARRAY['good coffee', 'fast wifi', 'networking', 'meeting rooms'], 'https://maps.app.goo.gl/commonmansg', 'https://commonmancoffeeroasters.com', NULL, 'buildermaps', true),
('singapore-nylon-coffee', 'Nylon Coffee Roasters', 'singapore', ARRAY['cafe'], 'Award-winning specialty coffee in Everton Park. Small but mighty space known for excellent single origins and a loyal following of coffee-loving founders.', ARRAY[103.8393, 1.2761], ARRAY['good coffee', 'quiet zone', 'deep focus', 'casual'], 'https://maps.app.goo.gl/nyloncoffee', 'https://nyloncoffee.sg', NULL, 'buildermaps', true),
('singapore-antler', 'Antler Singapore Hub', 'singapore', ARRAY['community'], 'Community hub for Antler portfolio companies and broader Singapore founder ecosystem. Regular demo days and investor networking events.', ARRAY[103.8468, 1.2850], ARRAY['founders only', 'networking', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/antlersg', 'https://antler.co', 'https://x.com/antaborler', 'buildermaps', true),
('singapore-startup-grind', 'Startup Grind Singapore', 'singapore', ARRAY['community'], 'Active chapter of global Startup Grind community. Monthly fireside chats with successful founders and strong networking opportunities.', ARRAY[103.8490, 1.2966], ARRAY['networking', 'events', 'mentorship', 'beginner friendly'], 'https://maps.app.goo.gl/startupgrindsg', 'https://startupgrind.com/singapore', 'https://x.com/startupgrindsg', 'buildermaps', true);

-- =====================================================
-- AUSTIN
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('austin-hacker-house-east', 'ATX Founder House', 'austin', ARRAY['hacker-house'], 'Coliving for founders relocating to Austin. East Austin location with strong community of SF/NYC transplants building in crypto and AI.', ARRAY[-97.7203, 30.2612], ARRAY['founders only', 'crypto crowd', 'ai builders', 'networking'], 'https://maps.app.goo.gl/atxfounderhouse', NULL, NULL, 'buildermaps', true),
('austin-merit-coffee', 'Merit Coffee', 'austin', ARRAY['cafe'], 'San Antonio-born specialty roaster with loyal Austin following. The South Congress location attracts tech workers with great coffee and ample seating.', ARRAY[-97.7506, 30.2502], ARRAY['good coffee', 'fast wifi', 'casual', 'outdoor seating'], 'https://maps.app.goo.gl/meritcoffee', 'https://meritcoffee.com', 'https://x.com/meritcoffee', 'buildermaps', true),
('austin-houndstooth', 'Houndstooth Coffee', 'austin', ARRAY['cafe'], 'Austin specialty coffee institution. The Frost Bank Tower location is a popular spot for downtown tech workers seeking quality espresso and focus time.', ARRAY[-97.7444, 30.2696], ARRAY['good coffee', 'fast wifi', 'deep focus', 'power outlets'], 'https://maps.app.goo.gl/houndstoothcoffee', 'https://houndstoothcoffee.com', NULL, 'buildermaps', true),
('austin-capital-factory', 'Capital Factory Community', 'austin', ARRAY['community'], 'Texas largest accelerator and startup community. Beyond coworking - regular founder programming, investor intros, and the heart of Austin tech scene.', ARRAY[-97.7394, 30.2687], ARRAY['networking', 'mentorship', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/capitalfactory', 'https://capitalfactory.com', 'https://x.com/capitalfactory', 'buildermaps', true),
('austin-techstars', 'Techstars Austin', 'austin', ARRAY['community'], 'Active Techstars community with regular events beyond just the accelerator. Strong mentor network and connections across Texas startup ecosystem.', ARRAY[-97.7431, 30.2672], ARRAY['networking', 'mentorship', 'events', 'vc sightings'], 'https://maps.app.goo.gl/techstarsaustin', 'https://techstars.com', 'https://x.com/techstars', 'buildermaps', true);

-- =====================================================
-- MIAMI
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('miami-hacker-house-wynwood', 'Miami Founder House', 'miami', ARRAY['hacker-house'], 'Coliving in Wynwood for tech founders. Strong crypto and fintech community with regular hackathons and investor events.', ARRAY[-80.1985, 25.8009], ARRAY['founders only', 'crypto crowd', 'networking', 'events'], 'https://maps.app.goo.gl/miamifounderhouse', NULL, NULL, 'buildermaps', true),
('miami-panther-coffee', 'Panther Coffee Wynwood', 'miami', ARRAY['cafe'], 'Miami specialty coffee pioneer. The Wynwood location is a tech hub with great outdoor seating and strong WiFi for working sessions.', ARRAY[-80.1991, 25.7997], ARRAY['good coffee', 'fast wifi', 'outdoor seating', 'networking'], 'https://maps.app.goo.gl/panthercoffee', 'https://panthercoffee.com', 'https://x.com/panthercoffee', 'buildermaps', true),
('miami-threefold-cafe', 'Threefold Cafe', 'miami', ARRAY['cafe'], 'Plant-based cafe in Coral Gables with health-conscious tech crowd. Great for meetings and focus work with excellent cold brew and reliable WiFi.', ARRAY[-80.2684, 25.7489], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'outdoor seating'], 'https://maps.app.goo.gl/threefoldcafe', 'https://threefoldcafe.com', NULL, 'buildermaps', true),
('miami-refresh', 'Refresh Miami', 'miami', ARRAY['community'], 'Miami original tech community organization. Weekly events, founder showcases, and strong connections across South Florida startup ecosystem.', ARRAY[-80.1918, 25.7617], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/refreshmiami', 'https://refreshmiami.com', 'https://x.com/refreshmiami', 'buildermaps', true),
('miami-500-startups', '500 Global Miami', 'miami', ARRAY['community'], 'Miami hub for 500 Global portfolio and community. Regular programming for Latin American founders entering US market.', ARRAY[-80.1917, 25.7823], ARRAY['networking', 'mentorship', 'vc sightings', 'events'], 'https://maps.app.goo.gl/500miami', 'https://500.co', 'https://x.com/500globalvc', 'buildermaps', true);

-- =====================================================
-- TORONTO
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('toronto-hacker-house-king', 'Founder Coliving Toronto', 'toronto', ARRAY['hacker-house'], 'Coliving for founders in King West. Strong AI and fintech community with connections to Toronto thriving tech ecosystem.', ARRAY[-79.3935, 43.6445], ARRAY['founders only', 'ai builders', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/foundercolivingto', NULL, NULL, 'buildermaps', true),
('toronto-pilot-coffee', 'Pilot Coffee Roasters', 'toronto', ARRAY['cafe'], 'Toronto specialty coffee roaster with multiple locations. The Te Miro location is popular with startup teams for its spacious layout and quality espresso.', ARRAY[-79.4011, 43.6509], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/pilotcoffee', 'https://pilotcoffeeroasters.com', 'https://x.com/pilotcoffee', 'buildermaps', true),
('toronto-jimmy-coffee', 'Jimmy Coffee', 'toronto', ARRAY['cafe'], 'Portland Avenue cafe with strong following among Toronto tech workers. Known for consistent coffee and work-friendly environment.', ARRAY[-79.4242, 43.6495], ARRAY['good coffee', 'fast wifi', 'casual', 'power outlets'], 'https://maps.app.goo.gl/jimmycoffee', 'https://jimmyscoffee.com', NULL, 'buildermaps', true),
('toronto-dmz', 'DMZ Toronto', 'toronto', ARRAY['community'], 'Top-ranked university incubator at Toronto Met. Strong community programming, mentor network, and connections to Canadian tech ecosystem.', ARRAY[-79.3799, 43.6577], ARRAY['networking', 'mentorship', 'demo days', 'beginner friendly'], 'https://maps.app.goo.gl/dmztoronto', 'https://dmz.torontomu.ca', 'https://x.com/thedmz', 'buildermaps', true),
('toronto-vector-institute', 'Vector Institute Community', 'toronto', ARRAY['community'], 'Hub for AI research and startup community. Regular events, paper readings, and connections to Toronto world-class AI talent pool.', ARRAY[-79.3925, 43.6529], ARRAY['ai builders', 'networking', 'events', 'deep focus'], 'https://maps.app.goo.gl/vectorinstitute', 'https://vectorinstitute.ai', 'https://x.com/vectorinstaboritute', 'buildermaps', true);

-- =====================================================
-- DUBAI
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('dubai-hacker-house-difc', 'DIFC Founder House', 'dubai', ARRAY['hacker-house'], 'Coliving for fintech founders in DIFC. Strong community of builders targeting MENA market with regular investor events.', ARRAY[55.2805, 25.2138], ARRAY['founders only', 'crypto crowd', 'networking', 'vc sightings'], 'https://maps.app.goo.gl/difcfounderhouse', NULL, NULL, 'buildermaps', true),
('dubai-specialty-batch', 'Specialty Batch', 'dubai', ARRAY['cafe'], 'Dubai specialty coffee destination in Al Quoz. Industrial setting attracts creative and tech crowd. Great for focus work and informal meetings.', ARRAY[55.2337, 25.1411], ARRAY['good coffee', 'fast wifi', 'deep focus', 'casual'], 'https://maps.app.goo.gl/specialtybatch', NULL, NULL, 'buildermaps', true),
('dubai-common-grounds', 'Common Grounds DIFC', 'dubai', ARRAY['cafe'], 'Specialty coffee in DIFC popular with finance and fintech professionals. Great location for meetings with solid WiFi.', ARRAY[55.2788, 25.2119], ARRAY['good coffee', 'fast wifi', 'networking', 'meeting rooms'], 'https://maps.app.goo.gl/commongroundsdifc', 'https://commongrounds.ae', NULL, 'buildermaps', true),
('dubai-hub71', 'Hub71 Community', 'dubai', ARRAY['community'], 'Abu Dhabi tech ecosystem extended into Dubai. Regular founder events and strong connections to sovereign wealth fund-backed initiatives.', ARRAY[55.2708, 25.2048], ARRAY['networking', 'vc sightings', 'events', 'mentorship'], 'https://maps.app.goo.gl/hub71dubai', 'https://hub71.com', 'https://x.com/hub71ad', 'buildermaps', true),
('dubai-astrolabs', 'AstroLabs Community', 'dubai', ARRAY['community'], 'Tech hub helping international startups launch in MENA. Strong community programming and connections to regional investors.', ARRAY[55.2725, 25.0982], ARRAY['networking', 'events', 'mentorship', 'beginner friendly'], 'https://maps.app.goo.gl/astrolabsdubai', 'https://astrolabs.com', 'https://x.com/astrolabs', 'buildermaps', true);

-- =====================================================
-- TEL AVIV
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('telaviv-hacker-house-rothschild', 'Startup House TLV', 'tel-aviv', ARRAY['hacker-house'], 'Coliving for founders on Rothschild Boulevard. Heart of Tel Aviv startup ecosystem with strong cybersecurity and deep tech community.', ARRAY[34.7726, 32.0644], ARRAY['founders only', 'networking', 'vc sightings', 'fast wifi'], 'https://maps.app.goo.gl/startuphouseatlv', NULL, NULL, 'buildermaps', true),
('telaviv-cafelix', 'Cafelix', 'tel-aviv', ARRAY['cafe'], 'Tel Aviv specialty coffee with strong tech following. Known for excellent espresso and work-friendly atmosphere in the Florentin neighborhood.', ARRAY[34.7688, 32.0553], ARRAY['good coffee', 'fast wifi', 'casual', 'outdoor seating'], 'https://maps.app.goo.gl/cafelix', NULL, NULL, 'buildermaps', true),
('telaviv-nahat', 'Nahat Coffee', 'tel-aviv', ARRAY['cafe'], 'Specialty coffee in Neve Tzedek popular with startup crowd. Great courtyard seating and reliable WiFi for work sessions.', ARRAY[34.7663, 32.0611], ARRAY['good coffee', 'fast wifi', 'outdoor seating', 'networking'], 'https://maps.app.goo.gl/nahatcoffee', NULL, NULL, 'buildermaps', true),
('telaviv-junction', 'The Junction', 'tel-aviv', ARRAY['community'], 'Tech community hub with regular events, workshops, and networking for Tel Aviv builders. Strong connections to Israeli VC ecosystem.', ARRAY[34.7818, 32.0853], ARRAY['networking', 'events', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/junctiontlv', 'https://junction.co.il', NULL, 'buildermaps', true),
('telaviv-8200-alumni', '8200 EISP Community', 'tel-aviv', ARRAY['community'], 'Community for IDF 8200 alumni building startups. Regular programming and strong network of Israeli tech veterans.', ARRAY[34.7900, 32.0700], ARRAY['founders only', 'networking', 'mentorship', 'events'], 'https://maps.app.goo.gl/8200eisp', 'https://8200eisp.com', 'https://x.com/8200_eisp', 'buildermaps', true);

-- =====================================================
-- SEOUL
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('seoul-hacker-house-gangnam', 'Seoul Founder House', 'seoul', ARRAY['hacker-house'], 'Coliving for international founders in Gangnam. Strong gaming and entertainment tech community with K-startup ecosystem connections.', ARRAY[127.0276, 37.4979], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/seoulfounderhouse', NULL, NULL, 'buildermaps', true),
('seoul-anthracite', 'Anthracite Coffee', 'seoul', ARRAY['cafe'], 'Industrial-chic specialty coffee in Hannam-dong. Popular with creative and tech crowd, known for excellent pour-overs and spacious seating.', ARRAY[127.0011, 37.5341], ARRAY['good coffee', 'fast wifi', 'deep focus', 'quiet zone'], 'https://maps.app.goo.gl/anthraciteseoul', NULL, NULL, 'buildermaps', true),
('seoul-fritz-coffee', 'Fritz Coffee Company', 'seoul', ARRAY['cafe'], 'Beloved Seoul specialty roaster. The Mapo location attracts startup workers with quality coffee and laptop-friendly environment.', ARRAY[126.9544, 37.5499], ARRAY['good coffee', 'fast wifi', 'casual', 'power outlets'], 'https://maps.app.goo.gl/fritzcoffee', 'https://fritzcoffeecompany.com', NULL, 'buildermaps', true),
('seoul-spark-labs', 'SparkLabs Community', 'seoul', ARRAY['community'], 'Leading Korean accelerator with strong community programming. Regular demo days, mentor sessions, and connections to Asian tech ecosystem.', ARRAY[127.0295, 37.4989], ARRAY['networking', 'mentorship', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/sparklabsseoul', 'https://sparklabs.co.kr', 'https://x.com/sparklabsgroup', 'buildermaps', true),
('seoul-google-campus', 'Google Campus Seoul', 'seoul', ARRAY['community'], 'Google-backed startup campus with regular events and programming. Strong connections to Korean corporate innovation initiatives.', ARRAY[127.0374, 37.4975], ARRAY['networking', 'events', 'beginner friendly', 'mentorship'], 'https://maps.app.goo.gl/googlecampusseoul', 'https://campus.co/seoul', NULL, 'buildermaps', true);

-- =====================================================
-- MUMBAI
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('mumbai-hacker-house-bandra', 'Mumbai Founder House', 'mumbai', ARRAY['hacker-house'], 'Coliving for founders in Bandra. Strong fintech and consumer tech community with connections to Mumbai investor ecosystem.', ARRAY[72.8323, 19.0596], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/mumbaifounderhouse', NULL, NULL, 'buildermaps', true),
('mumbai-blue-tokai', 'Blue Tokai Coffee Bandra', 'mumbai', ARRAY['cafe'], 'India specialty coffee pioneer. The Bandra location is a startup favorite with reliable WiFi and great cold brew.', ARRAY[72.8361, 19.0544], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/bluetokaimumbai', 'https://bluetokaicoffee.com', 'https://x.com/bluetokai', 'buildermaps', true),
('mumbai-koinonia', 'Koinonia Coffee Roasters', 'mumbai', ARRAY['cafe'], 'Specialty coffee in Lower Parel popular with startup crowd. Great for meetings and focused work with excellent espresso.', ARRAY[72.8296, 18.9967], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'meeting rooms'], 'https://maps.app.goo.gl/koinoniamumbai', 'https://koinoniacoffee.in', NULL, 'buildermaps', true),
('mumbai-nasscom', 'NASSCOM Community', 'mumbai', ARRAY['community'], 'Industry body with strong startup programming. Regular events, policy discussions, and connections to Indian tech ecosystem.', ARRAY[72.8777, 19.0760], ARRAY['networking', 'events', 'mentorship', 'vc sightings'], 'https://maps.app.goo.gl/nasscommumbai', 'https://nasscom.in', 'https://x.com/nasscom', 'buildermaps', true),
('mumbai-headstart', 'Headstart Network', 'mumbai', ARRAY['community'], 'Student and young founder community. Regular events, pitch competitions, and strong network for early-stage builders.', ARRAY[72.8656, 19.1136], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/headstartmumbai', 'https://headstart.in', 'https://x.com/headstartinfabor', 'buildermaps', true);

-- =====================================================
-- HONG KONG
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('hongkong-hacker-house-central', 'HK Founder Residency', 'hong-kong', ARRAY['hacker-house'], 'Coliving for founders in Central. Strong fintech and web3 community with connections to Greater China market.', ARRAY[114.1588, 22.2819], ARRAY['founders only', 'crypto crowd', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/hkfounderresidency', NULL, NULL, 'buildermaps', true),
('hongkong-cupping-room', 'The Cupping Room', 'hong-kong', ARRAY['cafe'], 'Specialty coffee pioneer in Hong Kong. Multiple locations with the Central spot popular among finance and fintech professionals.', ARRAY[114.1555, 22.2821], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/cuppingroomhk', 'https://cuppingroom.hk', NULL, 'buildermaps', true),
('hongkong-elephant-grounds', 'Elephant Grounds', 'hong-kong', ARRAY['cafe'], 'Popular specialty coffee with multiple locations. The Wan Chai spot attracts startup crowd with great ice cream and coffee.', ARRAY[114.1734, 22.2778], ARRAY['good coffee', 'fast wifi', 'casual', 'outdoor seating'], 'https://maps.app.goo.gl/elephantgroundshk', 'https://elephantgrounds.com', 'https://x.com/elephantgrounds', 'buildermaps', true),
('hongkong-cyberport', 'Cyberport Community', 'hong-kong', ARRAY['community'], 'Government-backed tech hub with strong community programming. Regular events, accelerator programs, and Greater Bay Area connections.', ARRAY[114.1302, 22.2614], ARRAY['networking', 'mentorship', 'events', 'vc sightings'], 'https://maps.app.goo.gl/cyberporthk', 'https://cyberport.hk', 'https://x.com/cyberport_hk', 'buildermaps', true),
('hongkong-startmeup', 'StartmeupHK Community', 'hong-kong', ARRAY['community'], 'Government initiative building Hong Kong startup ecosystem. Year-round programming and events including annual festival.', ARRAY[114.1694, 22.3193], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/startmeupahk', 'https://startmeup.hk', 'https://x.com/startmeuphk', 'buildermaps', true);

-- =====================================================
-- SYDNEY
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('sydney-hacker-house-surry', 'Sydney Founder House', 'sydney', ARRAY['hacker-house'], 'Coliving for founders in Surry Hills. Strong climate tech and fintech community with connections to Australian startup ecosystem.', ARRAY[151.2123, -33.8845], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/sydneyfounderhouse', NULL, NULL, 'buildermaps', true),
('sydney-single-o', 'Single O', 'sydney', ARRAY['cafe'], 'Sydney specialty coffee institution. The Surry Hills location is a known startup hangout with excellent coffee and work-friendly atmosphere.', ARRAY[151.2104, -33.8846], ARRAY['good coffee', 'fast wifi', 'networking', 'casual'], 'https://maps.app.goo.gl/singleosydney', 'https://singleo.com.au', NULL, 'buildermaps', true),
('sydney-paramount-coffee', 'Paramount Coffee Project', 'sydney', ARRAY['cafe'], 'Multi-roaster cafe in Surry Hills popular with creative and tech crowd. Spacious interior perfect for meetings or solo work.', ARRAY[151.2071, -33.8857], ARRAY['good coffee', 'fast wifi', 'meeting rooms', 'power outlets'], 'https://maps.app.goo.gl/paramountcoffee', 'https://paramountcoffeeproject.com.au', NULL, 'buildermaps', true),
('sydney-stone-chalk', 'Stone & Chalk Community', 'sydney', ARRAY['community'], 'Leading Australian fintech hub with strong community programming. Regular events, mentor access, and connections to APAC investors.', ARRAY[151.2055, -33.8611], ARRAY['networking', 'mentorship', 'vc sightings', 'events'], 'https://maps.app.goo.gl/stonechalkasydney', 'https://stoneandchalk.com.au', 'https://x.com/stoneandchalk', 'buildermaps', true),
('sydney-fishburners', 'Fishburners Community', 'sydney', ARRAY['community'], 'Long-running Sydney startup community. Regular events, mentorship, and strong alumni network across Australian tech.', ARRAY[151.1980, -33.8916], ARRAY['networking', 'events', 'beginner friendly', 'mentorship'], 'https://maps.app.goo.gl/fishburnerssydney', 'https://fishburners.org', 'https://x.com/fishburners', 'buildermaps', true);

-- =====================================================
-- TAIPEI
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('taipei-hacker-house-daan', 'Taipei Founder House', 'taipei', ARRAY['hacker-house'], 'Coliving for founders in Da an District. Strong hardware and semiconductor community with connections to Taiwan manufacturing ecosystem.', ARRAY[121.5434, 25.0268], ARRAY['founders only', 'networking', 'fast wifi', 'events'], 'https://maps.app.goo.gl/taipeifounderhouse', NULL, NULL, 'buildermaps', true),
('taipei-simple-kaffa', 'Simple Kaffa', 'taipei', ARRAY['cafe'], 'World Barista Champion cafe in Taipei. Known for exceptional coffee and work-friendly atmosphere in Huashan area.', ARRAY[121.5295, 25.0439], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'deep focus'], 'https://maps.app.goo.gl/simplekaffa', NULL, NULL, 'buildermaps', true),
('taipei-luguo-cafe', 'Luguo Cafe', 'taipei', ARRAY['cafe'], 'Specialty coffee in Zhongshan attracting digital nomads and local startups. Great pour-overs and reliable WiFi.', ARRAY[121.5245, 25.0552], ARRAY['good coffee', 'fast wifi', 'casual', 'power outlets'], 'https://maps.app.goo.gl/luguocafe', NULL, NULL, 'buildermaps', true),
('taipei-appworks', 'AppWorks Community', 'taipei', ARRAY['community'], 'Leading Southeast Asian accelerator with strong Taipei presence. Regular events and connections to greater Asia startup ecosystem.', ARRAY[121.5446, 25.0330], ARRAY['networking', 'mentorship', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/appworkstabori', 'https://appworks.tw', 'https://x.com/appaborworks', 'buildermaps', true),
('taipei-garage', 'Taipei Garage+', 'taipei', ARRAY['community'], 'Government-backed startup hub with international programming. Regular events connecting Taiwan startups to global markets.', ARRAY[121.5654, 25.0330], ARRAY['networking', 'events', 'beginner friendly', 'mentorship'], 'https://maps.app.goo.gl/taipeigarage', 'https://garage.tw', NULL, 'buildermaps', true);

-- =====================================================
-- JAKARTA
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('jakarta-hacker-house-kemang', 'Jakarta Founder House', 'jakarta', ARRAY['hacker-house'], 'Coliving for founders in Kemang. Strong e-commerce and fintech community targeting Indonesia massive market.', ARRAY[106.8161, -6.2615], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/jakartafounderhouse', NULL, NULL, 'buildermaps', true),
('jakarta-tanamera', 'Tanamera Coffee', 'jakarta', ARRAY['cafe'], 'Indonesian specialty coffee with multiple locations. The Kemang spot attracts startup crowd with quality single origins.', ARRAY[106.8145, -6.2598], ARRAY['good coffee', 'fast wifi', 'networking', 'casual'], 'https://maps.app.goo.gl/tanameracoffee', 'https://tanameracoffee.com', NULL, 'buildermaps', true),
('jakarta-anomali', 'Anomali Coffee', 'jakarta', ARRAY['cafe'], 'Pioneer of Indonesia specialty coffee scene. The Senopati location is popular with tech workers for focus work.', ARRAY[106.8023, -6.2406], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/anomalicoffee', 'https://anomalicoffee.com', NULL, 'buildermaps', true),
('jakarta-east-ventures', 'East Ventures Community', 'jakarta', ARRAY['community'], 'Leading SEA VC with strong founder community. Regular events, founder dinners, and connections across Indonesia ecosystem.', ARRAY[106.8456, -6.2088], ARRAY['networking', 'vc sightings', 'events', 'mentorship'], 'https://maps.app.goo.gl/eastventuresjakarta', 'https://east.vc', 'https://x.com/east_ventures', 'buildermaps', true),
('jakarta-block71', 'BLOCK71 Jakarta', 'jakarta', ARRAY['community'], 'Singapore-Indonesia startup connector. Regular events bridging Southeast Asian startup ecosystems.', ARRAY[106.8267, -6.2274], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/block71jakarta', 'https://block71.co', NULL, 'buildermaps', true);

-- =====================================================
-- Continue with remaining cities...
-- SAO PAULO
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('saopaulo-hacker-house-pinheiros', 'SP Founder House', 'sao-paulo', ARRAY['hacker-house'], 'Coliving for founders in Pinheiros. Strong fintech community targeting Brazil and LATAM markets.', ARRAY[-46.6840, -23.5631], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/spfounderhouse', NULL, NULL, 'buildermaps', true),
('saopaulo-coffee-lab', 'Coffee Lab', 'sao-paulo', ARRAY['cafe'], 'Specialty coffee pioneer in Sao Paulo. Known for exceptional quality and attracting coffee-loving tech workers.', ARRAY[-46.6731, -23.5630], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'deep focus'], 'https://maps.app.goo.gl/coffeelabsp', 'https://coffeelab.com.br', NULL, 'buildermaps', true),
('saopaulo-isso-e-cafe', 'Isso é Café', 'sao-paulo', ARRAY['cafe'], 'Specialty coffee with multiple locations. The Pinheiros spot is popular with startup teams for meetings and work.', ARRAY[-46.6860, -23.5671], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/issoecafe', 'https://issoecafe.com.br', NULL, 'buildermaps', true),
('saopaulo-cubo', 'Cubo Itau Community', 'sao-paulo', ARRAY['community'], 'Corporate-backed tech hub with strong programming. Regular events connecting startups with enterprises.', ARRAY[-46.6933, -23.5982], ARRAY['networking', 'vc sightings', 'events', 'mentorship'], 'https://maps.app.goo.gl/cuboitau', 'https://cubo.network', 'https://x.com/cubonetwork', 'buildermaps', true),
('saopaulo-distrito', 'Distrito Community', 'sao-paulo', ARRAY['community'], 'Leading Brazil startup community with data platform. Regular events and strong connections to LATAM ecosystem.', ARRAY[-46.6651, -23.5578], ARRAY['networking', 'events', 'demo days', 'vc sightings'], 'https://maps.app.goo.gl/distritosp', 'https://distrito.me', 'https://x.com/distritobr', 'buildermaps', true);

-- =====================================================
-- MEXICO CITY
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('mexicocity-hacker-house-roma', 'CDMX Founder House', 'mexico-city', ARRAY['hacker-house'], 'Coliving for founders in Roma Norte. Strong community of founders building for LATAM from Mexico City.', ARRAY[-99.1670, 19.4195], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/cdmxfounderhouse', NULL, NULL, 'buildermaps', true),
('mexicocity-chiquitito', 'Chiquitito Café', 'mexico-city', ARRAY['cafe'], 'Specialty coffee in Roma with strong following among digital nomads and local startups. Great for focus work.', ARRAY[-99.1646, 19.4207], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'casual'], 'https://maps.app.goo.gl/chiquitito', NULL, NULL, 'buildermaps', true),
('mexicocity-almanegra', 'Almanegra Café', 'mexico-city', ARRAY['cafe'], 'Specialty coffee in Juárez known for excellent espresso. Popular with tech workers for morning work sessions.', ARRAY[-99.1695, 19.4268], ARRAY['good coffee', 'fast wifi', 'power outlets', 'networking'], 'https://maps.app.goo.gl/almanegra', NULL, NULL, 'buildermaps', true),
('mexicocity-500-latam', '500 Global LATAM', 'mexico-city', ARRAY['community'], 'Hub for 500 Global LATAM portfolio and community. Strong programming for founders targeting Latin American markets.', ARRAY[-99.1831, 19.4268], ARRAY['networking', 'mentorship', 'vc sightings', 'events'], 'https://maps.app.goo.gl/500latam', 'https://500.co', 'https://x.com/500globalvc', 'buildermaps', true),
('mexicocity-startup-mexico', 'Startup México Community', 'mexico-city', ARRAY['community'], 'National accelerator with strong community programming. Regular events and connections to Mexican tech ecosystem.', ARRAY[-99.1693, 19.4070], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/startupmx', 'https://startupmexico.com', 'https://x.com/saborptupmexico', 'buildermaps', true);

-- =====================================================
-- BUENOS AIRES
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('buenosaires-hacker-house-palermo', 'BA Founder House', 'buenos-aires', ARRAY['hacker-house'], 'Coliving for founders in Palermo. Strong community building for LATAM with particular strength in remote work tools.', ARRAY[-58.4273, -34.5854], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/bafounderhouse', NULL, NULL, 'buildermaps', true),
('buenosaires-lattente', 'LAB Tostadores', 'buenos-aires', ARRAY['cafe'], 'Specialty coffee roaster in Palermo. Popular with startup teams for quality espresso and work-friendly environment.', ARRAY[-58.4301, -34.5847], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/labtostadores', NULL, NULL, 'buildermaps', true),
('buenosaires-cuervo', 'Cuervo Café', 'buenos-aires', ARRAY['cafe'], 'Specialty coffee in Chacarita with laptop-friendly policy. Known for great breakfast and reliable WiFi.', ARRAY[-58.4565, -34.5862], ARRAY['good coffee', 'fast wifi', 'casual', 'networking'], 'https://maps.app.goo.gl/cuervocafe', NULL, NULL, 'buildermaps', true),
('buenosaires-nxtp', 'NXTP Labs Community', 'buenos-aires', ARRAY['community'], 'Leading LATAM accelerator community. Regular events and strong network across South American tech ecosystem.', ARRAY[-58.3816, -34.6037], ARRAY['networking', 'mentorship', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/nxtplabs', 'https://nxtplabs.com', 'https://x.com/nxtplabs', 'buildermaps', true),
('buenosaires-endeavor', 'Endeavor Argentina', 'buenos-aires', ARRAY['community'], 'High-impact entrepreneurship network. Regular events connecting growth-stage founders with mentors and investors.', ARRAY[-58.3726, -34.6083], ARRAY['networking', 'mentorship', 'events', 'vc sightings'], 'https://maps.app.goo.gl/endeavorba', 'https://endeavor.org.ar', 'https://x.com/endeavorarg', 'buildermaps', true);

-- =====================================================
-- BOGOTA
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('bogota-hacker-house-chapinero', 'Bogota Founder House', 'bogota', ARRAY['hacker-house'], 'Coliving for founders in Chapinero. Growing community targeting Colombian and Andean markets.', ARRAY[-74.0614, 4.6466], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/bogotafounderhouse', NULL, NULL, 'buildermaps', true),
('bogota-azahar', 'Azahar Coffee', 'bogota', ARRAY['cafe'], 'Colombian specialty coffee showcasing local origins. Popular with startup teams in Chapinero area.', ARRAY[-74.0560, 4.6486], ARRAY['good coffee', 'fast wifi', 'networking', 'casual'], 'https://maps.app.goo.gl/azaharcoffee', 'https://azaharcoffee.com', NULL, 'buildermaps', true),
('bogota-pergamino', 'Pergamino Café', 'bogota', ARRAY['cafe'], 'Medellin-born specialty roaster with Bogota presence. Known for exceptional Colombian coffee and work-friendly vibe.', ARRAY[-74.0545, 4.6471], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/pergaminocafe', 'https://pergamino.co', NULL, 'buildermaps', true),
('bogota-rockstart', 'Rockstart Bogota', 'bogota', ARRAY['community'], 'European accelerator with Colombia presence. Regular events connecting founders with international investors.', ARRAY[-74.0721, 4.7110], ARRAY['networking', 'mentorship', 'vc sightings', 'events'], 'https://maps.app.goo.gl/rockstartbogota', 'https://rockstart.com', 'https://x.com/rockstart', 'buildermaps', true),
('bogota-innpulsa', 'iNNpulsa Community', 'bogota', ARRAY['community'], 'Government innovation agency with strong startup programming. Connections to Colombian entrepreneurship ecosystem.', ARRAY[-74.0568, 4.6528], ARRAY['networking', 'events', 'beginner friendly', 'mentorship'], 'https://maps.app.goo.gl/innpulsa', 'https://innpulsacolombia.com', 'https://x.com/innpulsacol', 'buildermaps', true);

-- =====================================================
-- LAGOS
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('lagos-hacker-house-vi', 'Lagos Founder House', 'lagos', ARRAY['hacker-house'], 'Coliving for founders in Victoria Island. Strong fintech community building for Nigerian and African markets.', ARRAY[3.4219, 6.4281], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/lagosfounderhouse', NULL, NULL, 'buildermaps', true),
('lagos-coffee-cabin', 'The Coffee Cabin', 'lagos', ARRAY['cafe'], 'Specialty coffee in Victoria Island popular with Lagos tech crowd. Great for meetings and focus work.', ARRAY[3.4245, 6.4325], ARRAY['good coffee', 'fast wifi', 'networking', 'power outlets'], 'https://maps.app.goo.gl/coffeecabinlagos', NULL, NULL, 'buildermaps', true),
('lagos-cafe-neo', 'Café Neo', 'lagos', ARRAY['cafe'], 'Nigerian specialty coffee chain with startup-friendly environment. Multiple locations across Lagos business districts.', ARRAY[3.4186, 6.4306], ARRAY['good coffee', 'fast wifi', 'meeting rooms', 'casual'], 'https://maps.app.goo.gl/cafeneolagos', 'https://cafeneo.com', NULL, 'buildermaps', true),
('lagos-techcabal', 'TechCabal Community', 'lagos', ARRAY['community'], 'Leading African tech media with strong community events. Regular programming connecting Nigerian tech ecosystem.', ARRAY[3.3792, 6.5244], ARRAY['networking', 'events', 'beginner friendly', 'demo days'], 'https://maps.app.goo.gl/techcabal', 'https://techcabal.com', 'https://x.com/techcabal', 'buildermaps', true),
('lagos-ventures-platform', 'Ventures Platform Community', 'lagos', ARRAY['community'], 'VC firm with strong founder community. Regular events, office hours, and connections to African investor ecosystem.', ARRAY[3.4217, 6.4323], ARRAY['networking', 'vc sightings', 'mentorship', 'events'], 'https://maps.app.goo.gl/venturesplatform', 'https://venturesplatform.com', 'https://x.com/venturesplatfrm', 'buildermaps', true);

-- =====================================================
-- NAIROBI
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('nairobi-hacker-house-westlands', 'Nairobi Founder House', 'nairobi', ARRAY['hacker-house'], 'Coliving for founders in Westlands. Strong mobile and fintech community building for East African markets.', ARRAY[36.8086, -1.2636], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/nairobifounderhouse', NULL, NULL, 'buildermaps', true),
('nairobi-artcaffe', 'Artcaffé Westgate', 'nairobi', ARRAY['cafe'], 'Popular cafe chain with reliable WiFi. The Westgate location attracts startup teams and remote workers.', ARRAY[36.8035, -1.2587], ARRAY['good coffee', 'fast wifi', 'meeting rooms', 'networking'], 'https://maps.app.goo.gl/artcaffenairobi', 'https://artcaffe.co.ke', NULL, 'buildermaps', true),
('nairobi-connect-coffee', 'Connect Coffee', 'nairobi', ARRAY['cafe'], 'Specialty coffee in Kilimani known for single-origin Kenyan beans. Popular with tech workers for focused work.', ARRAY[36.7883, -1.2896], ARRAY['good coffee', 'fast wifi', 'quiet zone', 'power outlets'], 'https://maps.app.goo.gl/connectcoffee', NULL, NULL, 'buildermaps', true),
('nairobi-ihub', 'iHub Community', 'nairobi', ARRAY['community'], 'Pioneer of African tech hubs. Regular events, mentorship, and connections across East African startup ecosystem.', ARRAY[36.7876, -1.2896], ARRAY['networking', 'events', 'beginner friendly', 'mentorship'], 'https://maps.app.goo.gl/ihubnairobi', 'https://ihub.co.ke', 'https://x.com/iaborhub', 'buildermaps', true),
('nairobi-pangea', 'Pangea Accelerator', 'nairobi', ARRAY['community'], 'Norwegian-African accelerator with strong Nairobi presence. Regular demo days and investor connections.', ARRAY[36.8219, -1.2921], ARRAY['networking', 'mentorship', 'vc sightings', 'demo days'], 'https://maps.app.goo.gl/pangeanairobi', 'https://pangeaaccelerator.com', NULL, 'buildermaps', true);

-- =====================================================
-- CAPE TOWN
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('capetown-hacker-house-woodstock', 'Cape Town Founder House', 'cape-town', ARRAY['hacker-house'], 'Coliving for founders in Woodstock. Strong community building for South African and African markets.', ARRAY[18.4480, -33.9268], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/ctfounderhouse', NULL, NULL, 'buildermaps', true),
('capetown-truth-coffee', 'Truth Coffee Roasting', 'cape-town', ARRAY['cafe'], 'Steampunk-themed specialty roaster named world best coffee shop. Great for meetings with fantastic espresso.', ARRAY[18.4249, -33.9242], ARRAY['good coffee', 'networking', 'casual', 'power outlets'], 'https://maps.app.goo.gl/truthcoffee', 'https://truthcoffee.com', NULL, 'buildermaps', true),
('capetown-rosetta', 'Rosetta Roastery', 'cape-town', ARRAY['cafe'], 'Specialty coffee in Woodstock attracting creative and tech crowd. Great for focus work with quality pour-overs.', ARRAY[18.4477, -33.9237], ARRAY['good coffee', 'fast wifi', 'deep focus', 'quiet zone'], 'https://maps.app.goo.gl/rosettaroastery', 'https://rosettaroastery.com', NULL, 'buildermaps', true),
('capetown-codebridge', 'Codebridge Community', 'cape-town', ARRAY['community'], 'Civic tech community in Cape Town. Regular events focused on using technology for social impact.', ARRAY[18.4241, -33.9249], ARRAY['networking', 'events', 'beginner friendly', 'open community'], 'https://maps.app.goo.gl/codebridge', 'https://codebridge.org.za', NULL, 'buildermaps', true),
('capetown-silicon-cape', 'Silicon Cape Initiative', 'cape-town', ARRAY['community'], 'Regional tech initiative building Cape Town ecosystem. Regular events and connections to South African investors.', ARRAY[18.4167, -33.9198], ARRAY['networking', 'events', 'mentorship', 'demo days'], 'https://maps.app.goo.gl/siliconcape', 'https://siliconcape.com', 'https://x.com/siliconcape', 'buildermaps', true);

-- =====================================================
-- CAIRO
-- =====================================================
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('cairo-hacker-house-maadi', 'Cairo Founder House', 'cairo', ARRAY['hacker-house'], 'Coliving for founders in Maadi. Growing community targeting Egyptian and MENA markets.', ARRAY[31.2571, 29.9583], ARRAY['founders only', 'networking', 'events', 'fast wifi'], 'https://maps.app.goo.gl/cairofounderhouse', NULL, NULL, 'buildermaps', true),
('cairo-left-bank', 'Left Bank', 'cairo', ARRAY['cafe'], 'Specialty coffee in Zamalek popular with Cairo tech scene. Great riverside location for meetings and work.', ARRAY[31.2233, 30.0566], ARRAY['good coffee', 'fast wifi', 'networking', 'outdoor seating'], 'https://maps.app.goo.gl/leftbankcairo', NULL, NULL, 'buildermaps', true),
('cairo-cilantro', 'Cilantro Café', 'cairo', ARRAY['cafe'], 'Popular local chain with work-friendly policy. Multiple locations with reliable WiFi across Cairo.', ARRAY[31.2357, 30.0444], ARRAY['good coffee', 'fast wifi', 'meeting rooms', 'casual'], 'https://maps.app.goo.gl/cilantrocairo', 'https://cilantrocafe.net', NULL, 'buildermaps', true),
('cairo-greca', 'GrEEK Campus Community', 'cairo', ARRAY['community'], 'Major Cairo tech hub with strong community programming. Regular events and connections to MENA ecosystem.', ARRAY[31.2378, 30.0298], ARRAY['networking', 'events', 'mentorship', 'demo days'], 'https://maps.app.goo.gl/greekcampus', 'https://greekcampus.com', 'https://x.com/gaborreekcampus', 'buildermaps', true),
('cairo-flat6labs', 'Flat6Labs Cairo', 'cairo', ARRAY['community'], 'Regional accelerator with strong Cairo presence. Regular demo days and connections to MENA investors.', ARRAY[31.2188, 30.0455], ARRAY['networking', 'mentorship', 'vc sightings', 'events'], 'https://maps.app.goo.gl/flat6labs', 'https://flat6labs.com', 'https://x.com/flat6labs', 'buildermaps', true);

-- =====================================================
-- REMAINING CITIES (Smaller presence - 3 spots each)
-- =====================================================

-- TALLINN
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('tallinn-hacker-house', 'Tallinn Founder House', 'tallinn', ARRAY['hacker-house'], 'Coliving in Old Town for founders building e-residency startups and European tech companies.', ARRAY[24.7453, 59.4370], ARRAY['founders only', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/tallinnfounderhouse', NULL, NULL, 'buildermaps', true),
('tallinn-reval', 'Reval Café', 'tallinn', ARRAY['cafe'], 'Popular local chain with great coffee and work-friendly atmosphere near tech district.', ARRAY[24.7536, 59.4370], ARRAY['good coffee', 'fast wifi', 'casual'], 'https://maps.app.goo.gl/revalcafe', NULL, NULL, 'buildermaps', true),
('tallinn-startup-estonia', 'Startup Estonia Community', 'tallinn', ARRAY['community'], 'Government-backed community connecting e-residents and local founders with resources and events.', ARRAY[24.7536, 59.4370], ARRAY['networking', 'events', 'beginner friendly'], 'https://maps.app.goo.gl/startupestonia', 'https://startupestonia.ee', 'https://x.com/startupestonia', 'buildermaps', true);

-- DUBLIN
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('dublin-hacker-house', 'Dublin Founder House', 'dublin', ARRAY['hacker-house'], 'Coliving near Silicon Docks for founders building European HQ operations from Dublin.', ARRAY[-6.2389, 53.3457], ARRAY['founders only', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/dublinfounderhouse', NULL, NULL, 'buildermaps', true),
('dublin-3fe', '3fe Coffee', 'dublin', ARRAY['cafe'], 'Dublin specialty coffee pioneer. Popular with tech workers from nearby offices for quality espresso.', ARRAY[-6.2483, 53.3433], ARRAY['good coffee', 'fast wifi', 'networking'], 'https://maps.app.goo.gl/3fecoffee', 'https://3fe.com', NULL, 'buildermaps', true),
('dublin-dogpatch', 'Dogpatch Labs Community', 'dublin', ARRAY['community'], 'Ireland largest startup hub with strong community programming and connections to European investors.', ARRAY[-6.2389, 53.3478], ARRAY['networking', 'events', 'vc sightings'], 'https://maps.app.goo.gl/dogpatchlabs', 'https://dogpatchlabs.com', 'https://x.com/dogpatchlabs', 'buildermaps', true);

-- BARCELONA
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('barcelona-hacker-house', 'Barcelona Founder House', 'barcelona', ARRAY['hacker-house'], 'Coliving in El Born for digital nomads and founders targeting European and LATAM markets.', ARRAY[2.1822, 41.3851], ARRAY['founders only', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/bcnfounderhouse', NULL, NULL, 'buildermaps', true),
('barcelona-satan', 'Satan Coffee Corner', 'barcelona', ARRAY['cafe'], 'Specialty coffee in El Raval with strong laptop culture. Popular with remote workers and startup teams.', ARRAY[2.1687, 41.3808], ARRAY['good coffee', 'fast wifi', 'casual'], 'https://maps.app.goo.gl/satancoffee', NULL, NULL, 'buildermaps', true),
('barcelona-pier01', 'Pier01 Community', 'barcelona', ARRAY['community'], 'Tech hub at the port with regular events connecting Barcelona startup ecosystem.', ARRAY[2.1859, 41.3752], ARRAY['networking', 'events', 'demo days'], 'https://maps.app.goo.gl/pier01bcn', 'https://barcelonatech.city', NULL, 'buildermaps', true);

-- ZURICH
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('zurich-hacker-house', 'Zurich Founder House', 'zurich', ARRAY['hacker-house'], 'Coliving for crypto and fintech founders building in Switzerland regulated environment.', ARRAY[8.5417, 47.3769], ARRAY['founders only', 'crypto crowd', 'networking'], 'https://maps.app.goo.gl/zurichfounderhouse', NULL, NULL, 'buildermaps', true),
('zurich-mame', 'MAME Coffee', 'zurich', ARRAY['cafe'], 'Specialty coffee near ETH attracting technical founders and AI researchers.', ARRAY[8.5478, 47.3774], ARRAY['good coffee', 'fast wifi', 'deep focus'], 'https://maps.app.goo.gl/mamecoffee', 'https://mamecoffee.ch', NULL, 'buildermaps', true),
('zurich-flab', 'F10 Community', 'zurich', ARRAY['community'], 'Swiss fintech accelerator with strong community events and banking industry connections.', ARRAY[8.5417, 47.3769], ARRAY['networking', 'vc sightings', 'events'], 'https://maps.app.goo.gl/f10zurich', 'https://f10.global', NULL, 'buildermaps', true);

-- SEATTLE
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('seattle-victrola', 'Victrola Coffee Roasters', 'seattle', ARRAY['cafe'], 'Seattle specialty institution on Capitol Hill. Popular with tech workers and founders for quality coffee.', ARRAY[-122.3210, 47.6145], ARRAY['good coffee', 'fast wifi', 'networking'], 'https://maps.app.goo.gl/victrolacoffee', 'https://victrolacoffee.com', NULL, 'buildermaps', true),
('seattle-elm-coffee', 'Elm Coffee Roasters', 'seattle', ARRAY['cafe'], 'Pioneer Square specialty roaster in beautiful space. Great for meetings and focused work.', ARRAY[-122.3336, 47.6015], ARRAY['good coffee', 'fast wifi', 'quiet zone'], 'https://maps.app.goo.gl/elmcoffee', 'https://elmcoffeeroasters.com', NULL, 'buildermaps', true),
('seattle-madrona', 'Madrona Venture Community', 'seattle', ARRAY['community'], 'Leading PNW VC with founder community events. Strong connections to Seattle enterprise tech ecosystem.', ARRAY[-122.3321, 47.6062], ARRAY['networking', 'vc sightings', 'mentorship'], 'https://maps.app.goo.gl/madronavc', 'https://madrona.com', 'https://x.com/madrona', 'buildermaps', true);

-- LOS ANGELES
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('losangeles-hacker-house', 'LA Founder House', 'los-angeles', ARRAY['hacker-house'], 'Coliving in Venice for founders building at the intersection of tech and entertainment.', ARRAY[-118.4695, 33.9850], ARRAY['founders only', 'networking', 'events'], 'https://maps.app.goo.gl/lafounderhouse', NULL, NULL, 'buildermaps', true),
('losangeles-verve', 'Verve Coffee Arts District', 'los-angeles', ARRAY['cafe'], 'Santa Cruz-born specialty roaster. The DTLA location attracts creative tech crowd.', ARRAY[-118.2296, 34.0457], ARRAY['good coffee', 'fast wifi', 'networking'], 'https://maps.app.goo.gl/vervecoffeela', 'https://vervecoffee.com', NULL, 'buildermaps', true),
('losangeles-amplify', 'Amplify LA Community', 'los-angeles', ARRAY['community'], 'Venice-based accelerator community with strong entertainment tech focus.', ARRAY[-118.4695, 33.9925], ARRAY['networking', 'demo days', 'vc sightings'], 'https://maps.app.goo.gl/amplaboryityla', 'https://amplify.la', 'https://x.com/amplify_la', 'buildermaps', true);

-- BOSTON
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('boston-hacker-house', 'Boston Founder House', 'boston', ARRAY['hacker-house'], 'Coliving in Cambridge for founders from MIT and Harvard startup ecosystem.', ARRAY[-71.0942, 42.3601], ARRAY['founders only', 'ai builders', 'networking'], 'https://maps.app.goo.gl/bostonfounderhouse', NULL, NULL, 'buildermaps', true),
('boston-gracenote', 'Gracenote Coffee', 'boston', ARRAY['cafe'], 'Tiny specialty spot in Leather District beloved by Boston tech workers.', ARRAY[-71.0548, 42.3515], ARRAY['good coffee', 'fast wifi', 'quiet zone'], 'https://maps.app.goo.gl/gracenotecoffee', NULL, NULL, 'buildermaps', true),
('boston-cic', 'CIC Cambridge Community', 'boston', ARRAY['community'], 'Kendall Square innovation hub with strong programming for biotech and deep tech founders.', ARRAY[-71.0842, 42.3625], ARRAY['networking', 'events', 'mentorship'], 'https://maps.app.goo.gl/ciccambridge', 'https://cic.com', NULL, 'buildermaps', true);

-- VANCOUVER
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('vancouver-hacker-house', 'Vancouver Founder House', 'vancouver', ARRAY['hacker-house'], 'Coliving in Gastown for founders building games, AI, and clean tech.', ARRAY[-123.1058, 49.2827], ARRAY['founders only', 'ai builders', 'networking'], 'https://maps.app.goo.gl/vanfounderhouse', NULL, NULL, 'buildermaps', true),
('vancouver-revolver', 'Revolver Coffee', 'vancouver', ARRAY['cafe'], 'Gastown specialty institution known for rotating guest roasters and tech-friendly atmosphere.', ARRAY[-123.1058, 49.2837], ARRAY['good coffee', 'fast wifi', 'networking'], 'https://maps.app.goo.gl/revolvercoffee', 'https://revolvercoffee.ca', NULL, 'buildermaps', true),
('vancouver-launch-academy', 'Launch Academy Community', 'vancouver', ARRAY['community'], 'Long-running Vancouver accelerator with strong community events.', ARRAY[-123.1216, 49.2827], ARRAY['networking', 'events', 'beginner friendly'], 'https://maps.app.goo.gl/launchacademy', 'https://launchacademy.ca', NULL, 'buildermaps', true);

-- SANTIAGO
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('santiago-hacker-house', 'Santiago Founder House', 'santiago', ARRAY['hacker-house'], 'Coliving in Providencia for founders targeting Chilean and South American markets.', ARRAY[-70.6141, -33.4324], ARRAY['founders only', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/santiagofounderhouse', NULL, NULL, 'buildermaps', true),
('santiago-cafe-altura', 'Café de la Barra', 'santiago', ARRAY['cafe'], 'Specialty coffee in Lastarria neighborhood popular with startup teams and digital nomads.', ARRAY[-70.6419, -33.4400], ARRAY['good coffee', 'fast wifi', 'casual'], 'https://maps.app.goo.gl/cafedelabarra', NULL, NULL, 'buildermaps', true),
('santiago-startup-chile', 'Startup Chile Community', 'santiago', ARRAY['community'], 'Government accelerator that put Chile on the startup map. Strong alumni network and regular events.', ARRAY[-70.6693, -33.4489], ARRAY['networking', 'events', 'mentorship'], 'https://maps.app.goo.gl/startupchile', 'https://startupchile.org', 'https://x.com/startupchile', 'buildermaps', true);

-- LIMA
INSERT INTO spots (id, name, city_id, types, description, coordinates, vibes, google_maps_url, website_url, twitter_url, added_by, approved) VALUES
('lima-hacker-house', 'Lima Founder House', 'lima', ARRAY['hacker-house'], 'Coliving in Miraflores for founders building for Peruvian and Andean markets.', ARRAY[-77.0282, -12.1211], ARRAY['founders only', 'networking', 'fast wifi'], 'https://maps.app.goo.gl/limafounderhouse', NULL, NULL, 'buildermaps', true),
('lima-origin', 'The Origin Coffee', 'lima', ARRAY['cafe'], 'Specialty coffee in Miraflores showcasing Peruvian single origins. Work-friendly atmosphere.', ARRAY[-77.0285, -12.1197], ARRAY['good coffee', 'fast wifi', 'casual'], 'https://maps.app.goo.gl/origincoffeelima', NULL, NULL, 'buildermaps', true),
('lima-utec', 'UTEC Ventures Community', 'lima', ARRAY['community'], 'University-backed innovation hub with regular events for Lima tech ecosystem.', ARRAY[-77.0428, -12.0464], ARRAY['networking', 'events', 'beginner friendly'], 'https://maps.app.goo.gl/utecventures', 'https://utecventures.com', NULL, 'buildermaps', true);
